// Tailwind aliases for the single CSS token source in app/globals.css.
// Legacy selectors may remain, but their p/t/g/r/n colors resolve there too.
import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    '*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      screens: {
        tablet: '768px',
        desktop: '1200px',
        wide: '1600px',
      },
      colors: {
        // Legacy ci-* consumers now share one CSS source instead of hardcoded copies.
        ci: {
          paper: 'var(--ci-paper)',
          'paper-2': 'var(--ci-paper-2)',
          white: 'var(--ci-white)',
          ink: 'var(--ci-ink)',
          'gray-700': 'var(--ci-gray-700)',
          'gray-600': 'var(--ci-gray-600)',
          'gray-500': 'var(--ci-gray-500)',
          'gray-400': 'var(--ci-gray-400)',
          border: 'var(--ci-border)',
          'border-2': 'var(--ci-border-2)',
          'blue-50': 'var(--ci-blue-50)',
          'blue-100': 'var(--ci-blue-100)',
          'blue-150': 'var(--ci-blue-150)',
          'blue-200': 'var(--ci-blue-200)',
          'blue-400': 'var(--ci-blue-400)',
          'blue-600': 'var(--ci-blue-600)',
          navy: 'var(--ci-navy)',
          'navy-700': 'var(--ci-navy-700)',
          'navy-900': 'var(--ci-navy-900)',
          accent: 'var(--ci-accent)',
          'accent-600': 'var(--ci-accent-600)',
          'accent-100': 'var(--ci-accent-100)',
          'accent-50': 'var(--ci-accent-50)',
        },
        student: {
          primary: 'var(--student-primary)',
          'primary-hover': 'var(--student-primary-hover)',
          'primary-text': 'var(--student-primary-text)',
          navigation: 'var(--student-navigation)',
          'navigation-deep': 'var(--student-navigation-deep)',
          'navigation-active': 'var(--student-navigation-active)',
          'navigation-text': 'var(--student-navigation-text)',
          'navigation-text-muted': 'var(--student-navigation-text-muted)',
          'navigation-hover': 'var(--student-navigation-hover)',
          'navigation-current': 'var(--student-navigation-current)',
          'navigation-outline': 'var(--student-navigation-outline)',
          'navigation-divider': 'var(--student-navigation-divider)',
          'navigation-ring': 'var(--student-navigation-ring)',
          accent: 'var(--student-accent)',
          'accent-hover': 'var(--student-accent-hover)',
          'accent-text': 'var(--student-accent-text)',
          'accent-strong': 'var(--student-accent-strong)',
          'accent-surface': 'var(--student-accent-surface)',
          'accent-border': 'var(--student-accent-border)',
          page: 'var(--student-page-surface)',
          'page-surface': 'var(--student-page-surface)',
          'page-glass': 'var(--student-page-glass)',
          'brand-surface': 'var(--student-brand-surface)',
          surface: 'var(--student-elevated-surface)',
          'elevated-surface': 'var(--student-elevated-surface)',
          'surface-muted': 'var(--student-surface-muted)',
          text: 'var(--student-text-primary)',
          'text-primary': 'var(--student-text-primary)',
          'text-secondary': 'var(--student-text-secondary)',
          'text-muted': 'var(--student-text-muted)',
          'text-faint': 'var(--student-text-faint)',
          link: 'var(--student-link)',
          border: 'var(--student-border)',
          'border-hover': 'var(--student-border-hover)',
          'border-strong': 'var(--student-border-strong)',
          'control-border': 'var(--student-control-border)',
          focus: 'var(--student-focus)',
          'focus-inverse': 'var(--student-focus-inverse)',
          success: 'var(--student-success)',
          'success-surface': 'var(--student-success-surface)',
          warning: 'var(--student-warning)',
          'warning-surface': 'var(--student-warning-surface)',
          error: 'var(--student-error)',
          'error-surface': 'var(--student-error-surface)',
          'error-text': 'var(--student-error-text)',
          disabled: 'var(--student-disabled)',
          'disabled-surface': 'var(--student-disabled-surface)',
          skeleton: 'var(--student-skeleton)',
          'signal-track': 'var(--student-signal-track)',
          'signal-track-inverse': 'var(--student-signal-track-inverse)',
          'motif-light-ring': 'var(--student-motif-light-ring)',
          signal: 'var(--student-signal)',
          'signal-strong': 'var(--student-signal-strong)',
          scrim: 'var(--student-scrim)',
        },
        // Legacy primary class names
        p: {
          50: 'var(--p-50)',
          100: 'var(--p-100)',
          300: 'var(--p-300)',
          500: 'var(--p-500)',
          600: 'var(--p-600)',
          700: 'var(--p-700)',
          900: 'var(--p-900)',
        },
        // Legacy signal class names
        t: {
          50: 'var(--t-50)',
          500: 'var(--t-500)',
          600: 'var(--t-600)',
          700: 'var(--t-700)',
        },
        // Independent success state
        g: {
          50: 'var(--g-50)',
          600: 'var(--g-600)',
          700: 'var(--g-700)',
        },
        // Independent error state
        r: {
          50: 'var(--r-50)',
          300: 'var(--r-300)',
          600: 'var(--r-600)',
          700: 'var(--r-700)',
        },
        // Legacy neutral class names
        n: {
          0: 'var(--n-0)',
          50: 'var(--n-50)',
          100: 'var(--n-100)',
          200: 'var(--n-200)',
          300: 'var(--n-300)',
          400: 'var(--n-400)',
          500: 'var(--n-500)',
          600: 'var(--n-600)',
          700: 'var(--n-700)',
          800: 'var(--n-800)',
          900: 'var(--n-900)',
        },
        // shadcn aliases — retained so legacy ui/* primitives still compile
        // while the redesign is in flight. CSS variables aren't defined right
        // now, so do not author new code against these tokens.
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      fontFamily: {
        // Hanken Grotesk is the default sans (Variant B). The --font-hanken var
        // is set by next/font in app/layout.tsx.
        sans: ['var(--font-hanken)', 'Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['var(--serif)'],
        mono: ['var(--mono)'],
      },
      maxWidth: {
        wrap: 'var(--maxw)',
        'ci-content': 'var(--ci-maxw)',
        'student-content': 'var(--student-maxw)',
      },
      boxShadow: {
        'ci-card': 'var(--ci-shadow-card)',
        'ci-soft': 'var(--ci-shadow-soft)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'ci-btn': 'var(--ci-radius-btn)',
        'ci-btn-sm': 'var(--ci-radius-btn-sm)',
        'ci-card': 'var(--ci-radius-card)',
        'ci-card-lg': 'var(--ci-radius-card-lg)',
        'ci-panel': 'var(--ci-radius-panel)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
export default config
