// scripts/managed-content/generate.cjs — Generate and verify the repository-content seed and DB parity test.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { buildManifest } = require('./source-manifest.cjs')

const ROOT = path.resolve(__dirname, '../..')
const SEED_PATH = path.join(ROOT, 'supabase/migrations/20261002130000_repository_content_seed.sql')
const TEST_PATH = path.join(ROOT, 'supabase/tests/repository_content_parity.test.sql')
const FAMILIES = ['course_overview', 'note', 'cbt_question', 'theory_question', 'model_answer', 'rubric']

function sqlLiteral(value) {
  return `'${value.replaceAll("'", "''")}'`
}

function jsonLiteral(value, tag) {
  const serialized = JSON.stringify(value)
  assert.ok(!serialized.includes(`$${tag}$`), `source content contains SQL delimiter ${tag}`)
  return `$${tag}$${serialized}$${tag}$::jsonb`
}

function seedSql(manifest) {
  return `-- supabase/migrations/20261002130000_repository_content_seed.sql
-- GENERATED by scripts/managed-content/generate.cjs from committed repository content.
-- The reserved actor UUID is a migration provenance marker, never an Auth account.
-- Replaying this seed skips unchanged migration-owned records and never rewrites operator edits.

create function private.replay_repository_content_seed()
returns void language plpgsql security invoker set search_path = '' as $repository_migration$
declare
  v_manifest jsonb := ${jsonLiteral(manifest, 'repository_source')};
  v_actor uuid := '${manifest.actor}'::uuid;
  v_course jsonb;
  v_item jsonb;
  v_existing public.managed_content_items%rowtype;
  v_parent uuid;
begin
  for v_course in select value from jsonb_array_elements(v_manifest->'courses') loop
    if not exists (
      select 1 from public.courses
      where id = (v_course->>'courseId')::uuid
        and content_key = v_course->>'contentKey'
    ) then
      raise exception 'Repository course identity mismatch: %', v_course->>'contentKey';
    end if;
  end loop;

  for v_item in select value from jsonb_array_elements(v_manifest->'items') loop
    v_parent := (v_item->>'parentItemId')::uuid;
    perform private.assert_managed_payload(v_item->>'kind', v_item->'payload');
    select * into v_existing from public.managed_content_items
      where id = (v_item->>'itemId')::uuid for update;
    if found then
      if v_existing.created_by is distinct from v_actor or
         v_existing.course_id is distinct from (v_item->>'courseId')::uuid or
         v_existing.kind is distinct from v_item->>'kind' or
         v_existing.question_id is distinct from (v_item->>'questionId')::uuid or
         v_existing.source_key is distinct from v_item->>'sourceKey' or
         v_existing.parent_item_id is distinct from v_parent or
         not exists (
           select 1 from public.managed_content_revisions r
           where r.item_id = v_existing.id and r.revision = 1
             and r.payload = v_item->'payload' and r.authored_by = v_actor
         ) or not exists (
           select 1 from public.managed_content_reviews r
           where r.item_id = v_existing.id and r.revision = 1
             and r.lock_version = 2 and r.decision = 'approved'
             and r.parent_revision is not distinct from
               case when v_parent is null then null else 1 end
             and r.reviewed_by = v_actor
         ) or not exists (
           select 1 from public.managed_content_publications p
           where p.item_id = v_existing.id and p.lock_version = 3
             and p.action = 'publish' and p.revision = 1
             and p.parent_revision is not distinct from
               case when v_parent is null then null else 1 end
             and p.acted_by = v_actor
         ) then
        raise exception 'Existing item is not the same migration-owned record: %',
          v_item->>'itemId';
      end if;
      continue;
    end if;

    insert into public.managed_content_items (
      id, course_id, kind, question_id, source_key, parent_item_id,
      current_revision, approved_revision, published_revision,
      published_parent_revision, lock_version, created_by
    ) values (
      (v_item->>'itemId')::uuid, (v_item->>'courseId')::uuid,
      v_item->>'kind', (v_item->>'questionId')::uuid,
      v_item->>'sourceKey', v_parent, 1, 1, 1,
      case when v_parent is null then null else 1 end, 3, v_actor
    );
    insert into public.managed_content_revisions (item_id, revision, payload, authored_by)
    values ((v_item->>'itemId')::uuid, 1, v_item->'payload', v_actor);
    insert into public.managed_content_reviews (
      item_id, revision, parent_revision, decision, reviewed_by, lock_version
    ) values (
      (v_item->>'itemId')::uuid, 1,
      case when v_parent is null then null else 1 end,
      'approved', v_actor, 2
    );
    insert into public.managed_content_publications (
      item_id, lock_version, action, revision, parent_revision, acted_by
    ) values (
      (v_item->>'itemId')::uuid, 3, 'publish', 1,
      case when v_parent is null then null else 1 end, v_actor
    );
  end loop;
end;
$repository_migration$;

revoke all on function private.replay_repository_content_seed()
  from public, anon, authenticated, service_role;
select private.replay_repository_content_seed();
`
}

function snapshot(item) {
  return {
    itemId: item.itemId, courseId: item.courseId, kind: item.kind,
    questionId: item.questionId, sourceKey: item.sourceKey,
    parentItemId: item.parentItemId, revision: 1, payload: item.payload,
  }
}

function testSql(manifest) {
  const lines = [
    '-- supabase/tests/repository_content_parity.test.sql — Generated source-to-published parity snapshots.',
    '-- GENERATED by scripts/managed-content/generate.cjs; do not hand-maintain.',
    'begin;',
    'select no_plan();',
    '',
    `select is((select count(*)::int from public.courses), ${manifest.courses.length},`,
    "  'every repository course identity is present');",
    `select ok((select jsonb_object_agg(content_key, id::text) from public.courses) = ${jsonLiteral(
      Object.fromEntries(manifest.courses.map(row => [row.contentKey, row.courseId])), 'registry_expected')},`,
    "  'repository UUIDs match the committed registry for every course');",
    '',
    'insert into auth.users (instance_id, id, aud, role, email, encrypted_password,',
    '  email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)',
    "values ('00000000-0000-0000-0000-000000000000',",
    "  '33333333-3333-4333-8333-333333333333', 'authenticated', 'authenticated',",
    "  'repository-parity-student@example.test', 'x', now(),",
    "  '{\"provider\":\"email\",\"providers\":[\"email\"]}', '{}', now(), now());",
    'insert into auth.sessions(id, user_id, created_at, updated_at) values',
    "  ('cccccccc-cccc-4ccc-8ccc-cccccccccccc',",
    "   '33333333-3333-4333-8333-333333333333', now(), now());",
    'set local role authenticated;',
    'set local request.jwt.claims =',
    "  '{\"sub\":\"33333333-3333-4333-8333-333333333333\",\"role\":\"authenticated\",\"session_id\":\"cccccccc-cccc-4ccc-8ccc-cccccccccccc\"}';",
    '',
  ]
  for (const course of manifest.courses) {
    for (const family of FAMILIES) {
      const expected = manifest.items.filter(item => item.courseId === course.courseId && item.kind === family)
        .sort((left, right) => left.sourceKey < right.sourceKey ? -1 : left.sourceKey > right.sourceKey ? 1 : 0)
        .map(snapshot)
      lines.push(`select ok((select coalesce(jsonb_agg(jsonb_build_object(`)
      lines.push("  'itemId', item_id, 'courseId', course_id, 'kind', kind,")
      lines.push("  'questionId', question_id, 'sourceKey', source_key,")
      lines.push("  'parentItemId', parent_item_id, 'revision', revision,")
      lines.push("  'payload', payload) order by source_key collate \"C\"), '[]'::jsonb)")
      lines.push(`  from public.read_published_managed_content('${course.courseId}')`)
      lines.push(`  where kind = '${family}') = ${jsonLiteral(expected, 'expected_content')},`)
      lines.push(`  ${sqlLiteral(`${course.contentKey}: ${family} published payload and identity match source`)});`)
    }
  }
  lines.push('', 'reset role;')
  lines.push(`select is((select count(*)::int from public.managed_content_items where created_by = '${manifest.actor}'),`)
  lines.push(`  ${manifest.items.length}, 'all source items carry migration provenance');`)
  lines.push(`select is((select count(*)::int from public.managed_content_items where created_by = '${manifest.actor}'`)
  lines.push('  and (current_revision <> 1 or approved_revision <> 1 or published_revision <> 1)),')
  lines.push("  0, 'all live repository items are approved and published at revision one');")
  lines.push(`select is((select count(*)::int from public.managed_content_reviews where reviewed_by = '${manifest.actor}'`)
  lines.push("  and decision = 'rejected'), 0, 'migration never publishes a rejected revision');")
  lines.push(`select is((select count(*)::int from public.managed_content_items i`)
  lines.push('  join public.managed_content_items parent on parent.id = i.parent_item_id')
  lines.push(`  where i.created_by = '${manifest.actor}' and i.kind = 'model_answer'`)
  lines.push('    and i.published_parent_revision is distinct from parent.published_revision),')
  lines.push("  0, 'every published model answer binds the published theory revision');")
  lines.push(`select is((select count(*)::int from public.managed_content_items where created_by = '${manifest.actor}'`)
  lines.push("  and kind = 'rubric'), 0, 'no source rubric was fabricated');")
  lines.push('select * from finish();', 'rollback;', '')
  return lines.join('\n')
}

const manifest = buildManifest()
const outputs = [[SEED_PATH, seedSql(manifest)], [TEST_PATH, testSql(manifest)]]
if (process.argv[2] === '--check') {
  for (const [filename, generated] of outputs) {
    assert.equal(fs.readFileSync(filename, 'utf8'), generated,
      `${path.relative(ROOT, filename)} is stale; regenerate from source`)
  }
  process.stdout.write(`Source-derived artifacts match ${manifest.items.length} items across ${manifest.courses.length} courses.\n`)
} else if (process.argv.length === 2) {
  for (const [filename, generated] of outputs) fs.writeFileSync(filename, generated)
  process.stdout.write(`Generated ${manifest.items.length} items across ${manifest.courses.length} courses.\n`)
} else {
  process.stderr.write('Usage: node scripts/managed-content/generate.cjs [--check]\n')
  process.exitCode = 2
}
